openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /v1/login:
        get:
            tags:
                - login
            summary: login login
            description: Login endpoint sets up the user for authentication and redirects them to the identity provider
            operationId: login#login
            parameters:
                - name: redirect
                  in: query
                  description: URL to be redirected to after logging in successfully
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: URL to be redirected to after logging in successfully
                    example: Minima quis numquam.
                  example: Excepturi quos ut.
                - name: api_client
                  in: query
                  description: The name of the api client which is requesting a token
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The name of the api client which is requesting a token
                    example: Sit et quaerat non nobis repudiandae autem.
                  example: Tempora vero.
                - name: Referer
                  in: header
                  description: Referer header value
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Referer header value
                    example: Provident ipsa dignissimos sed.
                  example: Est inventore.
            responses:
                "307":
                    description: Temporary Redirect response.
                    headers:
                        Location:
                            description: Location to redirect to for authentication
                            schema:
                                type: string
                                description: Location to redirect to for authentication
                                example: Cupiditate voluptatem a eaque odit.
                            example: Provident dignissimos.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult2'
                            example:
                                outcome: Tempore enim voluptatem unde cumque.
                "400":
                    description: Bad Request response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Nisi tempora delectus architecto.
                                outcome: Autem neque numquam.
                "401":
                    description: Unauthorized response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Debitis explicabo qui eveniet odio sit ducimus.
                                outcome: Quia qui.
                "500":
                    description: Internal Server Error response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Unde quod.
                                outcome: Laborum ut iste et harum.
    /v1/login/callback:
        get:
            tags:
                - login
            summary: callback login
            description: Callback endpoint that receives authorization code from identity provider
            operationId: login#callback
            parameters:
                - name: code
                  in: query
                  description: Authorization Code
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Authorization Code
                    example: Distinctio ut laboriosam nam hic vel vel.
                  example: Dignissimos repellendus quia.
                - name: state
                  in: query
                  description: State value
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: State value
                    example: Architecto et expedita eum voluptatibus tenetur non.
                  example: Odit deleniti non praesentium molestiae consequuntur.
            responses:
                "307":
                    description: Temporary Redirect response.
                    headers:
                        Location:
                            description: Location to redirect to for authentication
                            schema:
                                type: string
                                description: Location to redirect to for authentication
                                example: Eum molestiae ut deleniti laborum.
                            example: Voluptas commodi.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult2'
                            example:
                                outcome: Unde vero.
                "400":
                    description: Bad Request response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Dolorum aut aut impedit nisi odio.
                                outcome: Voluptate quod.
                "401":
                    description: Unauthorized response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Reiciendis voluptas in autem dolorem.
                                outcome: Et incidunt assumenda sequi.
                "500":
                    description: Internal Server Error response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResult'
                            example:
                                location: Velit rerum occaecati quia.
                                outcome: Odit nesciunt dicta tempore fugiat.
components:
    schemas:
        LoginResult:
            type: object
            properties:
                location:
                    type: string
                    description: Location to redirect to for authentication
                    example: Incidunt et ipsum facilis.
                outcome:
                    type: string
                    description: Login Result Outcome
                    example: Repudiandae tempore molestiae illo.
            example:
                location: Voluptas ipsum rerum iure minima nihil odio.
                outcome: Neque praesentium distinctio impedit perferendis aut.
        LoginResult2:
            type: object
            properties:
                outcome:
                    type: string
                    description: Login Result Outcome
                    example: Dolorem aut hic dolores est.
            example:
                outcome: Eaque nesciunt impedit aut rerum qui.
tags:
    - name: login
      description: Login Service
